spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/neobank360?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:neobank360_user}
    password: ${SPRING_DATASOURCE_PASSWORD:NeoBank360#}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: ${JWT_SECRET:neobank360secretkeyneobank360secretkeyneobank360secretkeyneobank360secretkey}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    org.springframework: INFO
    com.neobank: INFO
